- name: Install Snap
  become: true
  apt:
    name:
      - snapd
    state: present

- name: Install Snap core
  become: true
  command: snap install core

- name: Install Snap Store
  become: true
  command: snap install snap-store
