- name: Install fish
  become: yes
  apt:
    name: fish
    state: present

- name: Copy fish config
  copy:
    src: config.fish
    dest: "{{ansible_env.HOME}}/.config/fish"
    mode: 0664
    owner: "{{user}}"
    group: "{{user}}"

- name: default shell to fish
  become: yes
  user:
    name: "{{user}}"
    shell: /usr/bin/fish
