- name: Install vscodium
  become: true
  community.general.snap:
    name: codium
    classic: true

- name: Install vscodium extensions
  command: codium --install-extension {{ item }}
  loop:
    - aaron-bond.better-comments
    - angular.ng-template
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - firsttris.vscode-jest-runner
    - gabrielbb.vscode-lombok
    - mhutchie.git-graph
    - ms-azuretools.vscode-docker
    - ms-python.debugpy
    - ms-python.python
    - phil294.git-log--graph
    - redhat.ansible
    - redhat.fabric8-analytics
    - redhat.java
    - redhat.vscode-commons
    - redhat.vscode-yaml
    - sonarsource.sonarlint-vscode
    - timonwong.shellcheck
    - usernamehw.errorlens
    - vmware.vscode-spring-boot
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-spring-initializr
    - vscode-icons-team.vscode-icons
    - ziyasal.vscode-open-in-github

- name: Copy vscode user settings
  copy:
    src: settings.json
    dest: "{{ansible_env.HOME}}/.config/VSCodium/User/"
    mode: 0664
    owner: "{{user}}"
    group: "{{user}}"
