- name: Install flatpak
  become: yes
  apt:
    name:
      - flatpak
    state: present

- name: Add the flathub remote
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
