- name: Install zsh
  become: true
  apt:
    name: zsh
    state: present

- name: Copy zsh config
  copy:
    src: .zshrc
    dest: "{{ansible_env.HOME}}"
    mode: 0664
    owner: "{{user}}"
    group: "{{user}}"

- name: default shell to zsh
  become: true
  user:
    name: "{{user}}"
    shell: /bin/zsh
