- name: Install git
  become: true
  apt:
    name:
      - git
      - meld
      - gitg
    state: present

- name: Configure git username
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"

- name: Configure git email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: Configure mergetool
  community.general.git_config:
    name: merge.tool
    scope: global
    value: meld

- name: Configure difftool
  community.general.git_config:
    name: diff.tool
    scope: global
    value: meld

- name: Copy repo cleanup script
  copy:
    src: clean-repo.sh
    dest: "{{ ansible_env.HOME}}/bin/"
    mode: 0755
