- name: Install screen
  become: true
  apt:
    name:
      - screen
    state: present

- name: Copy configuration file for screen
  copy:
    src: .screenrc
    dest: "{{ansible_env.HOME}}"
    mode: 0664
    owner: "{{user}}"
    group: "{{user}}"
