- name: Install screen
  become: yes
  apt:
    name:
      - screen
    state: present

- name: Copy configuration file for screen
  copy:
    src: .screenrc
    dest: "/home/{{user}}/"
    mode: 0664
    owner: "{{user}}"
    group: "{{user}}"
